/*
 * Tabla.java
 *
 * Created on 5 de noviembre de 2008, 15:34
 */

package algoritmos;

import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author  32a08
 */
public class Tabla extends javax.swing.JFrame {
Vector v=new Vector(), cant=new Vector();
    /** Creates new form Tabla */
    public Tabla(Vector valor, Vector cantidad) {
        initComponents();
        tabla=new JTable(100,5);
        v=valor;
        v=cantidad;
        printear();
        
        setSize(500,500);
    }
    public void printear(){
        int fila=0;
        remove(scrtabla);
        tabla=new JTable(30,5);
	scrtabla=new JScrollPane(tabla);
	scrtabla.setBounds(10,10,470,320);
        add(scrtabla);
        
        if(v.size()>0){
            do{
                tabla.setValueAt(String.valueOf(v.elementAt(fila)).toString(),fila,0);
                tabla.setValueAt(String.valueOf(cant.elementAt(fila)).toString(),fila,1);
                fila++;
            }while(fila<v.size());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrtabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrtabla.setViewportView(tabla);

        getContentPane().add(scrtabla);
        scrtabla.setBounds(10, 10, 470, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrtabla;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
