package clinicamedica;
import java.sql.*;
import java.io.*;
import javax.swing.*;
/*
 * Gestion.java
 *
 * Created on 1 de octubre de 2008, 19:36
 */



/**
 *
 * @author  32a08
 */
public class Gestion extends javax.swing.JFrame {
String drv="sun.jdbc.odbc.JdbcOdbcDriver";
String dbs="jdbc:odbc:Gestion";
JOptionPane optAviso;
    /** Creates new form Gestion */
    public Gestion() {
        initComponents();
        this.setSize(350,200);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmblogin = new javax.swing.JComboBox();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN CLINICA");
        setName("frame0"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Seleccione su tipo de login (PACIENTE/MEDICO):");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 300, 14);

        cmblogin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PACIENTE", "MEDICO" }));
        getContentPane().add(cmblogin);
        cmblogin.setBounds(30, 30, 280, 22);
        getContentPane().add(txtcodigo);
        txtcodigo.setBounds(120, 90, 110, 19);

        jLabel2.setText("DNI/CODMEDICO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 70, 100, 20);

        btnconectar.setText("Login");
        btnconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconectar);
        btnconectar.setBounds(140, 130, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconectarActionPerformed
// TODO add your handling code here:
    String modo;
    boolean encontro=false;
    String nom=null,ape=null,doc=null,dir=null,historia=null,tel=null,nac=null;
    
    modo=(String)cmblogin.getSelectedItem();
    
    if(modo.compareTo("PACIENTE")==0){
       try{
            Class.forName(drv);
    
            Connection cnx=DriverManager.getConnection(dbs);
    
            Statement stm= cnx.createStatement();
    
            ResultSet rst=stm.executeQuery("SELECT Nombre,Apellido,Documento FROM Pacientes");
    
                while((rst.next()) && (!encontro)){
                    //System.out.println(rst.wasNull());
                    //if(!rst.wasNull()){    
                        nom=rst.getString("Nombre");
                        ape=rst.getString("Apellido");
                        doc=rst.getString("Documento");
                        if(doc.compareTo(txtcodigo.getText())==0){
                            encontro=true;
                        }
                    //}
                }
    
                if(encontro){
                    optAviso.showMessageDialog(null,"Bienvenido Paciente "+ape+", "+nom,"Login Exitoso",optAviso.WARNING_MESSAGE);
                    new Paciente(nom,ape,doc).setVisible(true);
                }else{
                    optAviso.showMessageDialog(null,"Verifique el CODIGO y el Tipo de login","Paciente no encontrado",optAviso.WARNING_MESSAGE);
                    new RegistroPaciente(txtcodigo.getText()).setVisible(true);
                    
                }
            encontro=false;
            rst.close();
            stm.close();
            cnx.close();
    }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
    }catch(SQLException sqle){
            sqle.printStackTrace();
    }
    }else{
        if(modo.compareTo("MEDICO")==0){
            try{
               // System.out.println("etapa1");
                Class.forName(drv);
               // System.out.println("etapa2");
                Connection cnx=DriverManager.getConnection(dbs);
               // System.out.println("etapa3");
                Statement stm= cnx.createStatement();
               // System.out.println("etapa4");
                ResultSet rst=stm.executeQuery("SELECT Codigo, Nombre,Apellido FROM Medicos");
              //  System.out.println("etapa5");

                while(rst.next() && !encontro){
               //     System.out.println("etapa6");
                    doc=rst.getString("Codigo");                        
                    //System.out.println("etapa7");
                    nom=rst.getString("Nombre");
                    //System.out.println("etapa8");
                    ape=rst.getString("Apellido");
                    //System.out.println("etapa9");
                    if(doc.compareTo(txtcodigo.getText())==0){
                        encontro=true;
                    }
                }
                //System.out.println("etapa10");
                if(encontro){
                    optAviso.showMessageDialog(null,"Bienvenido Medico "+ape+", "+nom,"Login Exitoso",optAviso.WARNING_MESSAGE);
                    new Medico(doc,nom,ape).setVisible(true);
                }else{
                    optAviso.showMessageDialog(null,"Verifique el CODIGO y el Tipo de login","Medico no encontrado",optAviso.WARNING_MESSAGE);
                    new RegistroMedico().setVisible(true);
                }
                encontro=false;
                rst.close();
                stm.close();
                cnx.close();
            }catch(ClassNotFoundException cnfe){
                    cnfe.printStackTrace();
            }catch(SQLException sqle){
                    sqle.printStackTrace();
            }    
            }
    }
}//GEN-LAST:event_btnconectarActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconectar;
    private javax.swing.JComboBox cmblogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables

}
