/*
 * HistoriaClinica.java
 *
 * Created on 9 de octubre de 2008, 15:30
 */

package clinicamedica;

import java.io.*;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author  32a08
 */
public class HistoriaClinica extends javax.swing.JFrame {
String dni;
String nom, ape;
JOptionPane aviso;

    /** Creates new form HistoriaClinica */
    public HistoriaClinica(String codpaciente,String nombre, String apellido) {
        initComponents();

        setSize(425,400);

        nom=nombre;
        ape=apellido;
        dni=codpaciente;
        
        cargarHistoria();
        
    }
    public void guardarHistoria(){
        Date dia=new Date();
        try{
            File f=new File("U:\\Trimestre 3\\Clinica Medica\\historias\\"+dni+".dat");
            ObjectOutputStream ois=new ObjectOutputStream(new FileOutputStream(f));
            if(txthistoria.getText().compareTo("")!=0){
                ois.writeObject(lbltexto.getText()+"\n"+"El medico "+ape+", "+nom+" anoto el "+dia.getDate()+"/"+dia.getMonth()+"/"+String.valueOf(dia.getYear()+1900).toString()+":\n"+txthistoria.getText());
                aviso.showMessageDialog(null,"Se ha creado/guardado el archivo exitosamente","Archivo guardado",aviso.INFORMATION_MESSAGE);
                ois.close();
                cargarHistoria();
            }

        }catch(IOException ioe){
            aviso.showMessageDialog(null,"Se ha producido un error imprevisto","Error Archivo",aviso.ERROR_MESSAGE);
        }
    }
    public void cargarHistoria(){
        try{
            File f=new File("U:\\Trimestre 3\\Clinica Medica\\historias\\"+dni+".dat");
            ObjectInputStream ois=new ObjectInputStream(new FileInputStream(f));
            
            lbltexto.setText((String)ois.readObject());
            
            ois.close();
        }catch(IOException ioe){
            System.out.println("ERROR GRABADO");
            guardarHistoria();
        }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
            aviso.showMessageDialog(null,"Se ha producido un error imprevisto","Error Archivo",aviso.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpaciente = new javax.swing.JLabel();
        scrtexto = new javax.swing.JScrollPane();
        txthistoria = new javax.swing.JTextArea();
        btnguardar = new javax.swing.JButton();
        scrhistoria = new javax.swing.JScrollPane();
        lbltexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HISTORIA CLINICA");
        getContentPane().setLayout(null);

        lblpaciente.setText("HISTORIA CLINICA: ");
        getContentPane().add(lblpaciente);
        lblpaciente.setBounds(10, 10, 410, 14);

        txthistoria.setColumns(20);
        txthistoria.setRows(5);
        scrtexto.setViewportView(txthistoria);

        getContentPane().add(scrtexto);
        scrtexto.setBounds(10, 220, 400, 70);

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(133, 300, 110, 23);

        lbltexto.setColumns(20);
        lbltexto.setEditable(false);
        lbltexto.setRows(5);
        lbltexto.setEnabled(false);
        scrhistoria.setViewportView(lbltexto);

        getContentPane().add(scrhistoria);
        scrhistoria.setBounds(10, 30, 400, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    guardarHistoria();
}//GEN-LAST:event_btnguardarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel lblpaciente;
    private javax.swing.JTextArea lbltexto;
    private javax.swing.JScrollPane scrhistoria;
    private javax.swing.JScrollPane scrtexto;
    private javax.swing.JTextArea txthistoria;
    // End of variables declaration//GEN-END:variables

}
