/*
 * HistoriaTurnos.java
 *
 * Created on 5 de noviembre de 2008, 20:22
 */

package clinicamedica;

import java.io.*;

/**
 *
 * @author  32a08
 */
public class HistoriaTurnos extends javax.swing.JFrame {

    /** Creates new form HistoriaTurnos */
    public HistoriaTurnos() {
        initComponents();
        cargarDatos();
        setSize(400,400);
    }
    public void cargarDatos(){
            try{
            File f=new File("U:\\Trimestre 3\\Clinica Medica\\historias\\ht.dat");
            ObjectInputStream ois=new ObjectInputStream(new FileInputStream(f));
            txthistoria.setText((String)ois.readObject());
            ois.close();
        }catch(IOException ioe){
            /*ioe.printStackTrace();
            jopaviso.showMessageDialog(null,"Se ha producido un error imprevisto","Error Archivo",jopaviso.ERROR_MESSAGE);*/
        }catch(ClassNotFoundException cnfe){
            /*cnfe.printStackTrace();
            jopaviso.showMessageDialog(null,"Se ha producido un error imprevisto","Error Archivo",jopaviso.ERROR_MESSAGE);*/
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrhistoria = new javax.swing.JScrollPane();
        txthistoria = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        txthistoria.setColumns(20);
        txthistoria.setEditable(false);
        txthistoria.setRows(5);
        txthistoria.setEnabled(false);
        scrhistoria.setViewportView(txthistoria);

        getContentPane().add(scrhistoria);
        scrhistoria.setBounds(10, 10, 380, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrhistoria;
    private javax.swing.JTextArea txthistoria;
    // End of variables declaration//GEN-END:variables

}
