/*
 * Paciente.java
 *
 * Created on 6 de octubre de 2008, 19:44
 */

package clinicamedica;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author  32a08
 */
public class Paciente extends javax.swing.JFrame {
    String drv="sun.jdbc.odbc.JdbcOdbcDriver";
    String dbs="jdbc:odbc:Gestion";
    String nom,ape,doc;
    JOptionPane jopaviso;
    static int esp;
    /** Creates new form Paciente */
    public Paciente(String nombre,String apellido,String documento) {
        initComponents();
        nom=nombre;
        ape=apellido;
        doc=documento;
        
        cargarDatos();
        cargarTurno();
        setSize(500,400);
        setVisible(true);
    }
public void cargarTurno(){
        try{
            Class.forName(drv);

            Connection cnx=DriverManager.getConnection(dbs);

            Statement stm= cnx.createStatement();

            ResultSet rst=stm.executeQuery("SELECT Nombre FROM Especialidades");
                cmbespecialidad.addItem("");
                while(rst.next()){
                    cmbespecialidad.addItem(rst.getString("Nombre"));
                }
    
            rst.close();
            stm.close();
            cnx.close();
        }catch(ClassNotFoundException cnfe){
                cnfe.printStackTrace();
        }catch(SQLException sqle){
                sqle.printStackTrace();
        }
    }
    public void cargarDatos(){
        try{
            Class.forName(drv);

            Connection cnx=DriverManager.getConnection(dbs);

            Statement stm= cnx.createStatement();

            ResultSet rst=stm.executeQuery("SELECT Nombre,Apellido,Direccion,Telefono,FechaNac,Documento FROM Pacientes WHERE Nombre='"+nom+"' AND Apellido='"+ape+"' AND Documento='"+doc+"'");

                while(rst.next()){
                    lblnombre.setText(lblnombre.getText()+"   "+rst.getString("Nombre"));
                    lblapellido.setText(lblapellido.getText()+"   "+rst.getString("Apellido"));
                    lbldireccion.setText(lbldireccion.getText()+"   "+rst.getString("Direccion"));
                    lbltelefono.setText(lbltelefono.getText()+"   "+rst.getString("Telefono"));
                    lblfechanac.setText(lblfechanac.getText()+"   "+rst.getString("FechaNac"));
                    lbldocumento.setText(lbldocumento.getText()+"   "+rst.getString("Documento"));
                }
    
            rst.close();
            stm.close();
            cnx.close();
    }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
    }catch(SQLException sqle){
            sqle.printStackTrace();
    }
    }
    public void cargarDoctor(int especialidad){
        try{
            Class.forName(drv);

            Connection cnx=DriverManager.getConnection(dbs);

            Statement stm= cnx.createStatement();

            ResultSet rst=stm.executeQuery("SELECT Apellido FROM Medicos WHERE CodEspecialidad="+String.valueOf(especialidad).toString()+"");
                if(!rst.wasNull()){
                    while(rst.next()){
                        cmbdoctor.addItem(rst.getString("Apellido"));
                    }
                }
            rst.close();
            stm.close();
            cnx.close();
        }catch(ClassNotFoundException cnfe){
                cnfe.printStackTrace();
        }catch(SQLException sqle){
                sqle.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbldocumento = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblfechanac = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbespecialidad = new javax.swing.JComboBox();
        cmbdoctor = new javax.swing.JComboBox();
        cmbdia = new javax.swing.JComboBox();
        cmbhora = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnturno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PACIENTE");
        setResizable(false);
        getContentPane().setLayout(null);

        lblnombre.setText("Nombre:");
        getContentPane().add(lblnombre);
        lblnombre.setBounds(40, 30, 250, 14);

        lblapellido.setText("Apellido:");
        getContentPane().add(lblapellido);
        lblapellido.setBounds(40, 50, 250, 14);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS PACIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 14);

        lbldocumento.setText("Documento:");
        getContentPane().add(lbldocumento);
        lbldocumento.setBounds(40, 70, 250, 14);

        lbltelefono.setText("Telefono:");
        getContentPane().add(lbltelefono);
        lbltelefono.setBounds(40, 110, 250, 14);

        lbldireccion.setText("Direccion:");
        getContentPane().add(lbldireccion);
        lbldireccion.setBounds(40, 90, 250, 14);

        lblfechanac.setText("Fecha Nacimiento:");
        getContentPane().add(lblfechanac);
        lblfechanac.setBounds(40, 130, 250, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TURNOS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 170, 460, 14);

        cmbespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbespecialidadActionPerformed(evt);
            }
        });
        getContentPane().add(cmbespecialidad);
        cmbespecialidad.setBounds(5, 230, 120, 22);

        cmbdoctor.setEnabled(false);
        cmbdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdoctorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbdoctor);
        cmbdoctor.setBounds(140, 230, 110, 22);

        cmbdia.setEnabled(false);
        getContentPane().add(cmbdia);
        cmbdia.setBounds(270, 230, 90, 22);

        cmbhora.setEnabled(false);
        getContentPane().add(cmbhora);
        cmbhora.setBounds(380, 230, 70, 22);

        jLabel3.setText("Especialidad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 210, 110, 14);

        jLabel4.setText("Doctor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 210, 110, 14);

        jLabel5.setText("Dia:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 210, 90, 14);

        jLabel6.setText("Hora:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 210, 70, 14);

        btnturno.setText("Pedir Turno");
        btnturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnturnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnturno);
        btnturno.setBounds(173, 270, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbespecialidadActionPerformed
// TODO add your handling code here:
    String especialidad;
    
    especialidad=(String)cmbespecialidad.getSelectedItem();
    if(!cmbdoctor.isEnabled()){
        cmbdoctor.setEnabled(true);

    }
    cmbdoctor.removeAllItems();        
    cmbdoctor.addItem("");
    if(cmbhora.isEnabled()&& cmbdia.isEnabled()){
        cmbhora.removeAllItems();
        cmbdia.removeAllItems();
    }
    if(especialidad.compareTo("Pediatria")==0){
        cargarDoctor(1);
        esp=1;
    }else{
        if(especialidad.compareTo("Odontologia")==0){
            cargarDoctor(2);
            esp=2;
        }else{
            if(especialidad.compareTo("Ginecologia")==0){
                cargarDoctor(3);
                esp=3;
            }else{
                if(especialidad.compareTo("Cardiologia")==0){
                    cargarDoctor(4);
                    esp=4;
                }else{
                    if(especialidad.compareTo("Neurologia")==0){
                        cargarDoctor(5);
                        esp=5;
                    }else{
                       if(especialidad.compareTo("Psiquiatria")==0){
                        cargarDoctor(6);
                        esp=6;
                       }
                    }
                }
            }
        }
    }
}//GEN-LAST:event_cmbespecialidadActionPerformed

private void cmbdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdoctorActionPerformed
// TODO add your handling code here:
String dias=null;
String horac=null,horaf=null;
String horacom=null,mincom=null,horafin=null,minfin=null;
int hc=0,hf=0,mc=0,mf=0;
int z;
if(cmbdoctor.getItemAt(0)!=null){
    if(((String)cmbdoctor.getSelectedItem()).compareTo("")!=0){
        if((!cmbhora.isEnabled()&&(!cmbdia.isEnabled()))){
            cmbhora.setEnabled(true);
            cmbdia.setEnabled(true);
            cmbhora.addItem("");
            cmbdia.addItem("");
        }else{
            cmbhora.removeAllItems();
            cmbdia.removeAllItems();
        }
        try{
                Class.forName(drv);

                Connection cnx=DriverManager.getConnection(dbs);

                Statement stm= cnx.createStatement();

                ResultSet rst=stm.executeQuery("SELECT HoraComienzo,HoraFin,Dias FROM Medicos WHERE Apellido='"+String.valueOf(cmbdoctor.getSelectedItem()).toString()+"'AND CodEspecialidad="+esp+"");
                    if(!rst.wasNull()){
                        while(rst.next()){
                            dias=(rst.getString("Dias"));
                            horac=rst.getString("HoraComienzo");
                            horaf=rst.getString("HoraFin");
                        }
                    }
                rst.close();
                stm.close();
                cnx.close();
            }catch(ClassNotFoundException cnfe){
                    cnfe.printStackTrace();
            }catch(SQLException sqle){
                    sqle.printStackTrace();
            }
           //System.out.println("horac"+horac);
           horacom=horac.substring(0,2);
           //System.out.println("horacom"+horacom);
           //System.out.println("horaf"+horaf);
           horafin=(horaf.substring(0,2));
           //System.out.println("horafin"+horafin);
           hc=Integer.parseInt(horacom);
           hf=Integer.parseInt(horafin);
            
            minfin=horaf.substring(3,5);
            //System.out.println("minfin"+minfin);
            mincom=horac.substring(3,5);
            //System.out.println("mincom"+mincom);
            mf=Integer.parseInt(minfin);
            //System.out.println("OK");
            mc=Integer.parseInt(mincom);

        for(z=0;z<(hf-hc);z++){
            cmbhora.addItem(String.valueOf(hc+z).toString()+":"+mincom);
        }
        if(mc!=mf){
            cmbhora.addItem(String.valueOf(hc+z).toString()+":"+minfin);
        }else{
            cmbhora.addItem(String.valueOf(hc+z).toString()+":"+minfin);
        }
        z=0;
        for(int x=0;x<dias.length();x++){
            if(dias.charAt(x)=='L'){
                cmbdia.addItem("Lunes");
            }else{
                if(dias.charAt(x)=='J'){
                    cmbdia.addItem("Jueves");
                }else{
                    if(dias.charAt(x)=='V'){
                        cmbdia.addItem("Viernes");
                    }else{
                        if(dias.charAt(x)=='M'){
                            z++;
                        }
                    }
                }
            }
        }
        switch(z){
            case 1:
                cmbdia.addItem("Martes");
                break;
            case 2:
                cmbdia.addItem("Miercoles");
                break;
            case 3:
                cmbdia.addItem("Martes");
                cmbdia.addItem("Miercoles");
                break;
        }
    }
}
}//GEN-LAST:event_cmbdoctorActionPerformed

private void btnturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnturnoActionPerformed
// TODO add your handling code here:
String pacienteturno=null,diaturno=null,auxiliar=null;
int espturno=0,medicoturno=0;
boolean esta=false;
if(cmbespecialidad.getSelectedIndex()>0 && cmbdia.getSelectedIndex()>0 && cmbdoctor.getSelectedIndex()>0 && cmbhora.getSelectedIndex()>0){
    try{
        Class.forName(drv);

        Connection cnx=DriverManager.getConnection(dbs);

        Statement stm= cnx.createStatement();

        ResultSet rst=stm.executeQuery("SELECT Codigo FROM Especialidades WHERE Nombre='"+((String)cmbespecialidad.getSelectedItem())+"'");
        if(rst.wasNull()){
            jopaviso.showMessageDialog(null,"En el Area "+((String)cmbespecialidad.getSelectedItem())+" no se encuentran medicos disponibles","Turno error",jopaviso.WARNING_MESSAGE);
        }else{
            rst.next();
            auxiliar=rst.getString("Codigo");
            espturno=Integer.parseInt(auxiliar);
        }
        stm.close();
        cnx.close();
    }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
    }catch(SQLException sqle){
            sqle.printStackTrace();
    }
    try{
        Class.forName(drv);

        Connection cnx=DriverManager.getConnection(dbs);

        Statement stm= cnx.createStatement();

        ResultSet rst=stm.executeQuery("SELECT Codigo FROM Medicos WHERE Apellido='"+((String)cmbdoctor.getSelectedItem())+"'AND CodEspecialidad="+espturno+"");
        
        if(rst.wasNull()){
            jopaviso.showMessageDialog(null,"En el Area "+((String)cmbespecialidad.getSelectedItem())+" no se encuentran medicos disponibles","Turno error",jopaviso.WARNING_MESSAGE);
        }else{
            rst.next();
            medicoturno=Integer.parseInt(rst.getString("Codigo"));
        }
        stm.close();
        cnx.close();
    }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
    }catch(SQLException sqle){
            sqle.printStackTrace();
    }    
    pacienteturno=(lbldocumento.getText()).substring(13,(lbldocumento.getText()).length());
    //System.out.println(pacienteturno);
    
    if(((String)cmbdia.getSelectedItem()).compareTo("Lunes")==0){
        diaturno="L";
    }else{
        if(((String)cmbdia.getSelectedItem()).compareTo("Martes")==0){
            diaturno="M";
        }else{
            if(((String)cmbdia.getSelectedItem()).compareTo("Miercoles")==0){
                diaturno="MM";
            }else{
                if(((String)cmbdia.getSelectedItem()).compareTo("Jueves")==0){
                    diaturno="J";
                }else{
                    if(((String)cmbdia.getSelectedItem()).compareTo("Viernes")==0){
                        diaturno="V";
                    }
                }
            }
        }
    }
    esta=false;
    try{
        Class.forName(drv);

        Connection cnx=DriverManager.getConnection(dbs);

        Statement stm= cnx.createStatement();

        ResultSet rst=stm.executeQuery("SELECT CodPaciente FROM Turnos WHERE Dia='"+diaturno+"' AND HoraComienzo='"+((String)cmbhora.getSelectedItem())+"' AND CodEspecialidad="+espturno+" AND CodMedico="+medicoturno+" AND CodPaciente='"+pacienteturno+"'");
        
        if(rst.wasNull()){
            jopaviso.showMessageDialog(null,"En el Area "+((String)cmbespecialidad.getSelectedItem())+" con el medico "+((String)cmbdoctor.getSelectedItem())+"a las "+((String)cmbhora.getSelectedItem())+" el dia "+((String)cmbdia.getSelectedItem())+" no se encuentra disponible","Turno error",jopaviso.WARNING_MESSAGE);
            esta=false;
        }else{
            try{
                rst.next();
                auxiliar=rst.getString("CodPaciente");            
                if(pacienteturno.compareTo(auxiliar)==0){
                    esta=true;    
                }
            }catch(SQLException sqle){
                esta=false;
            }

            
        }
        
        stm.close();
        cnx.close();
    }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
    }catch(SQLException sqle){
            sqle.printStackTrace();
    } 
    if(!esta){
        try{
            Class.forName(drv);

            Connection cnx=DriverManager.getConnection(dbs);

            Statement stm= cnx.createStatement();

            int rst=stm.executeUpdate("INSERT into Turnos (Dia,HoraComienzo,CodEspecialidad,CodMedico,CodPaciente) values('"+diaturno+"','"+((String)cmbhora.getSelectedItem())+"',"+espturno+","+medicoturno+",'"+pacienteturno+"')");
            jopaviso.showMessageDialog(null,"Area: "+((String)cmbespecialidad.getSelectedItem())+"\nMédico: "+((String)cmbdoctor.getSelectedItem())+"\nHora: "+((String)cmbhora.getSelectedItem())+"\nDia: "+((String)cmbdia.getSelectedItem())+"\nSe ha creado el turno","Turno exitoso",jopaviso.WARNING_MESSAGE);
            stm.close();
            cnx.close();
        }catch(ClassNotFoundException cnfe){
                cnfe.printStackTrace();
        }catch(SQLException sqle){
                sqle.printStackTrace();
        }
    }else{
        jopaviso.showMessageDialog(null,"Area: "+((String)cmbespecialidad.getSelectedItem())+"\nMédico: "+((String)cmbdoctor.getSelectedItem())+"\nHora: "+((String)cmbhora.getSelectedItem())+"\nDia: "+((String)cmbdia.getSelectedItem())+"\nNo se encuentra disponible","Turno error",jopaviso.WARNING_MESSAGE);
    }
}else{
    jopaviso.showMessageDialog(null,"Debe indicar todos los campos","Turno error",jopaviso.WARNING_MESSAGE);
}
}//GEN-LAST:event_btnturnoActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnturno;
    private javax.swing.JComboBox cmbdia;
    private javax.swing.JComboBox cmbdoctor;
    private javax.swing.JComboBox cmbespecialidad;
    private javax.swing.JComboBox cmbhora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JLabel lblfechanac;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltelefono;
    // End of variables declaration//GEN-END:variables

}
