/*
 * Calculadora.java
 *
 * Created on 15 de septiembre de 2008, 20:46
 */
package calculadora2;

/**
 *
 * @author  32a08
 */
public class Calculadora extends javax.swing.JFrame {

    static String operacion = "nada";
    static double valor1;
    static double valor2;
    static boolean decimal = false;

    /** Creates new form Calculadora */
    public Calculadora() {
        initComponents();
        this.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplica = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        graficador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora IVAN");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        pantalla.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        siete.setText("7");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        multiplica.setText("*");
        multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        potencia.setText("^");
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        graficador.setText("Graficador");
        graficador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficadorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pantalla, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(cinco)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(seis))
                                .add(layout.createSequentialGroup()
                                    .add(tres)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(cuatro))
                                .add(layout.createSequentialGroup()
                                    .add(siete)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(ocho))
                                .add(layout.createSequentialGroup()
                                    .add(nueve)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(cero)))
                            .add(layout.createSequentialGroup()
                                .add(uno)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dos)))
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(graficador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(suma, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(multiplica, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(punto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(potencia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .add(resta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, divide, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .add(igual, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))))
                .add(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pantalla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(uno)
                            .add(dos)
                            .add(resta))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cuatro)
                            .add(tres)
                            .add(divide))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cinco)
                            .add(seis)
                            .add(potencia))
                        .add(5, 5, 5)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(siete)
                            .add(ocho)
                            .add(graficador))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nueve)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(cero)
                                .add(igual))))
                    .add(layout.createSequentialGroup()
                        .add(suma)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(multiplica)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(punto)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
// TODO add your handling code here:
    System.out.println("Uno");//GEN-LAST:event_formKeyReleased

    }

private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
// TODO add your handling code here:

    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "1");
}//GEN-LAST:event_unoActionPerformed

private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
// TODO add your handling code here:

    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "2");
}//GEN-LAST:event_dosActionPerformed

private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "3");
}//GEN-LAST:event_tresActionPerformed

private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "4");
}//GEN-LAST:event_cuatroActionPerformed

private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "5");
}//GEN-LAST:event_cincoActionPerformed

private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "6");
}//GEN-LAST:event_seisActionPerformed

private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "7");
}//GEN-LAST:event_sieteActionPerformed

private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "8");
}//GEN-LAST:event_ochoActionPerformed

private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "9");
}//GEN-LAST:event_nueveActionPerformed

private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    pantalla.setText(pantalla.getText() + "0");
}//GEN-LAST:event_ceroActionPerformed

private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
// TODO add your handling code here:
    operacion = "suma";
    valor1 = Double.parseDouble(pantalla.getText());
    pantalla.setText("");
    decimal = false;
}//GEN-LAST:event_sumaActionPerformed

private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
// TODO add your handling code here:
    operacion = "resta";
    valor1 = Double.parseDouble(pantalla.getText());
    pantalla.setText("");
    decimal = false;
}//GEN-LAST:event_restaActionPerformed

private void multiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaActionPerformed
// TODO add your handling code here:
    operacion = "multiplicacion";
    valor1 = Double.parseDouble(pantalla.getText());
    pantalla.setText("");
    decimal = false;
}//GEN-LAST:event_multiplicaActionPerformed

private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
// TODO add your handling code here:
    operacion = "division";
    valor1 = Double.parseDouble(pantalla.getText());
    pantalla.setText("");
    decimal = false;
}//GEN-LAST:event_divideActionPerformed

private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
// TODO add your handling code here:
    operacion = "potencia";
    valor1 = Double.parseDouble(pantalla.getText());
    pantalla.setText("");
    decimal = false;
}//GEN-LAST:event_potenciaActionPerformed

private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
// TODO add your handling code here:
    valor2 = Double.parseDouble(pantalla.getText());
    if (operacion.compareTo("suma") == 0) {
        pantalla.setText(String.valueOf(valor1 + valor2).toString());
        operacion = "borrar";
        decimal = false;
    }
    if (operacion.compareTo("resta") == 0) {
        pantalla.setText(String.valueOf(valor1 - valor2).toString());
        operacion = "borrar";
        decimal = false;
    }
    if (operacion.compareTo("multiplicacion") == 0) {
        pantalla.setText(String.valueOf(valor1 * valor2).toString());
        operacion = "borrar";
        decimal = false;
    }
    if(operacion.compareTo("division")==0){//GEN-LAST:event_igualActionPerformed
        pantalla.setText(String.valueOf(valor1 / valor2).toString());
        operacion = "borrar";
        decimal = false;
    }
    if (operacion.compareTo("potencia") == 0) {
        pantalla.setText(String.valueOf(Math.pow(valor1, valor2)).toString());
        operacion = "borrar";
        decimal = false;
    }
}

private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
// TODO add your handling code here:
    if (operacion.compareTo("borrar") == 0) {
        pantalla.setText("");
        operacion = "nada";
    }
    if (!decimal) {
        decimal = true;
        if (pantalla.getText().compareTo("") == 0) {
            pantalla.setText(pantalla.getText() + "0.");
        } else {
            pantalla.setText(pantalla.getText() + ".");
        }
    }
}//GEN-LAST:event_puntoActionPerformed

private void graficadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficadorActionPerformed
// TODO add your handling code here:
    new Graficador().setVisible(true);
}//GEN-LAST:event_graficadorActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton divide;
    private javax.swing.JButton dos;
    private javax.swing.JButton graficador;
    private javax.swing.JButton igual;
    private javax.swing.JButton multiplica;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton potencia;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
