/*
 * Graficador.java
 *
 * Created on 17 de septiembre de 2008, 19:56
 */

package calculadora2;

/**
 *
 * @author  32a08
 */
public class Graficador extends javax.swing.JFrame {
    Micanvas mc=new Micanvas();
    /** Creates new form Graficador */
    public Graficador() {
        initComponents();
        setSize(650,600);
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seno = new javax.swing.JButton();
        coseno = new javax.swing.JButton();
        tangente = new javax.swing.JButton();
        polinomico = new javax.swing.JButton();
        gradoscroll = new javax.swing.JScrollPane();
        grado = new javax.swing.JList();
        grado3 = new javax.swing.JTextField();
        grado2 = new javax.swing.JTextField();
        grado1 = new javax.swing.JTextField();
        independiente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cargar = new javax.swing.JButton();
        dibujo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graficador IVAN");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        seno.setText("sen(x)");
        seno.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoActionPerformed(evt);
            }
        });
        getContentPane().add(seno);
        seno.setBounds(10, 10, 70, 23);

        coseno.setText("cos(x)");
        coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosenoActionPerformed(evt);
            }
        });
        getContentPane().add(coseno);
        coseno.setBounds(120, 10, 70, 23);

        tangente.setText("tg(x)");
        tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangenteActionPerformed(evt);
            }
        });
        getContentPane().add(tangente);
        tangente.setBounds(230, 10, 70, 23);

        polinomico.setText("Polinomica");
        polinomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polinomicoActionPerformed(evt);
            }
        });
        getContentPane().add(polinomico);
        polinomico.setBounds(340, 10, 100, 23);

        gradoscroll.setBorder(new javax.swing.border.MatteBorder(null));

        grado.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Grado 1", "Grado 2", "Grado 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        grado.setEnabled(false);
        gradoscroll.setViewportView(grado);

        getContentPane().add(gradoscroll);
        gradoscroll.setBounds(50, 60, 130, 20);

        grado3.setText("0");
        grado3.setEnabled(false);
        getContentPane().add(grado3);
        grado3.setBounds(240, 60, 60, 19);

        grado2.setText("0");
        grado2.setEnabled(false);
        getContentPane().add(grado2);
        grado2.setBounds(330, 60, 60, 19);

        grado1.setText("0");
        grado1.setEnabled(false);
        getContentPane().add(grado1);
        grado1.setBounds(420, 60, 60, 19);

        independiente.setText("0");
        independiente.setEnabled(false);
        getContentPane().add(independiente);
        independiente.setBounds(510, 60, 60, 19);

        jLabel1.setText("Numero x^3      Numero x^2      Numero x           Independiente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 40, 370, 14);

        cargar.setText("Cargar datos");
        cargar.setEnabled(false);
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        getContentPane().add(cargar);
        cargar.setBounds(480, 10, 110, 23);

        dibujo.setBorder(javax.swing.BorderFactory.createTitledBorder("Grafico"));
        getContentPane().add(dibujo);
        dibujo.setBounds(10, 90, 590, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoActionPerformed
// TODO add your handling code here:
    dibujo.remove(mc);
    mc=new Micanvas("seno",0,0,0,0);
    mc.setBounds(20,20,500,400);
    dibujo.add(mc);
}//GEN-LAST:event_senoActionPerformed

private void cosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosenoActionPerformed
// TODO add your handling code here:
    dibujo.remove(mc);
    mc=new Micanvas("coseno",0,0,0,0);
    mc.setBounds(20,20,500,400);
    dibujo.add(mc);
}//GEN-LAST:event_cosenoActionPerformed

private void tangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangenteActionPerformed
// TODO add your handling code here:
    dibujo.remove(mc);
    mc=new Micanvas("tangente",0,0,0,0);
    mc.setBounds(20,20,500,400);
    dibujo.add(mc);
}//GEN-LAST:event_tangenteActionPerformed

private void polinomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polinomicoActionPerformed
// TODO add your handling code here:
    cargar.setEnabled(true);
    grado.setEnabled(true);
    grado1.setEnabled(true);
    grado2.setEnabled(true);
    grado3.setEnabled(true);
    independiente.setEnabled(true);
}//GEN-LAST:event_polinomicoActionPerformed

private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
// TODO add your handling code here:
    double a=(double)0,b=(double)0,c=(double)0,d=(double)0;
    try{
        a=Double.parseDouble(grado3.getText());
    }catch(NumberFormatException nfe){
        a=(double)0;
        grado3.setText("0");
    }
    try{
        b=Double.parseDouble(grado2.getText());
    }catch(NumberFormatException nfe){
        b=(double)0;
        grado2.setText("0");
    }
    try{
        c=Double.parseDouble(grado1.getText());
    }catch(NumberFormatException nfe){
        c=(double)0;
        grado1.setText("0");
    }
    try{
        d=Double.parseDouble(independiente.getText());
    }catch(NumberFormatException nfe){
        d=(double)0;
        independiente.setText("0");
    }
    a=0;
    b=0;
    c=0;
    d=0;
    switch(grado.getSelectedIndex()){
        case 0:
            c=Double.parseDouble(grado1.getText());
            d=Double.parseDouble(independiente.getText());
            dibujo.remove(mc);
            mc=new Micanvas("polinomica",a,b,c,d);
            mc.setBounds(20,20,500,400);
            dibujo.add(mc);
            break;
        case 1:
            b=Double.parseDouble(grado2.getText());
            c=Double.parseDouble(grado1.getText());
            d=Double.parseDouble(independiente.getText());
            dibujo.remove(mc);
            mc=new Micanvas("polinomica",a,b,c,d);
            mc.setBounds(20,20,500,400);
            dibujo.add(mc);
            break;
        case 2:
            a=Double.parseDouble(grado3.getText());
            b=Double.parseDouble(grado2.getText());
            c=Double.parseDouble(grado1.getText());
            d=Double.parseDouble(independiente.getText());
            dibujo.remove(mc);
            mc=new Micanvas("polinomica",a,b,c,d);
            mc.setBounds(20,20,500,400);
            dibujo.add(mc);
            break;
        case -1:
            System.out.print("Error");
            break;
    }
}//GEN-LAST:event_cargarActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JButton coseno;
    private javax.swing.JPanel dibujo;
    private javax.swing.JList grado;
    private javax.swing.JTextField grado1;
    private javax.swing.JTextField grado2;
    private javax.swing.JTextField grado3;
    private javax.swing.JScrollPane gradoscroll;
    private javax.swing.JTextField independiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton polinomico;
    private javax.swing.JButton seno;
    private javax.swing.JButton tangente;
    // End of variables declaration//GEN-END:variables

}
